package sample.hibernate.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.ToString;

// Generated 08.02.2010 11:07:40 by Hibernate Tools 3.2.4.GA


/**
 * Dbinfo generated by hbm2java
 */
@Entity
@ToString
@Table(name = "DBINFO")
public class Dbinfo implements java.io.Serializable {

    private static final long serialVersionUID = -2488385949092609064L;
    private int id;
    private String dbversion;
    private String creationdate;

    public Dbinfo() {
    }

    public Dbinfo(int id, String dbversion, String creationdate) {
        this.id = id;
        this.dbversion = dbversion;
        this.creationdate = creationdate;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "DBVERSION", nullable = false)
    public String getDbversion() {
        return this.dbversion;
    }

    public void setDbversion(String dbversion) {
        this.dbversion = dbversion;
    }

    @Column(name = "CREATIONDATE", nullable = false)
    public String getCreationdate() {
        return this.creationdate;
    }

    public void setCreationdate(String creationdate) {
        this.creationdate = creationdate;
    }

}
